name: Send emails daily
on:
  workflow_dispatch: # manually
  schedule: # periodically
    - cron: '0 23 * * *'

jobs:
  search-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Run script
        env:
          SEND_EMPTY: ${{ vars.SEND_EMPTY }}
          MAX_RESULTS: ${{ secrets.MAX_RESULTS }}
          ARXIV_KEYWORD: ${{ secrets.ARXIV_QUERY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: |
          pip3 install -r requirements.txt
          python3 main.py
